# Generated by Django 2.2.6 on 2019-11-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='AboutPost',
        ),
    ]
