# Generated by Django 2.2.6 on 2019-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20191109_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpost',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='aboutpost',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
