# Generated by Django 2.2.6 on 2019-11-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title_ru',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
