# Generated by Django 2.2.6 on 2019-11-08 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
